### ISSUE TITLE
run main error 

### ISSUE THREAD

**Issue by 11721206** [Huang-Chuan/magnetic-field-odometry#1]
![image](https://user-images.githubusercontent.com/19368412/205252072-240f1f59-fb8d-4d01-aa54-f72280b01a02.png)
Thanks for your work,When I run main.m ,an error occurs.

**Comment by 11721206** [comment]
undefined function or variable: quaternion

**Comment by Huang-Chuan** [comment]
Please install corresponding toolbox, see [this link](https://se.mathworks.com/help/nav/ref/quaternion.html)
